Here's an example of using the code in dataDownload.py to download daily Google Trends data

In [3]:
import dataDownload as dd

df_tslaTrend = dd.get_daily_data(
    word="Tesla",
    start_year=2010,
    start_mon=6,
    start_day=30,
    stop_year=2021,
    stop_mon=3,
    stop_day=22
)

df_tslaTrend.head()

Tesla:2010-06-30 2010-06-30
Tesla:2010-07-01 2010-07-31
Tesla:2010-08-01 2010-08-31
Tesla:2010-09-01 2010-09-30
Tesla:2010-10-01 2010-10-31
Tesla:2010-11-01 2010-11-30
Tesla:2010-12-01 2010-12-31
Tesla:2011-01-01 2011-01-31
Tesla:2011-02-01 2011-02-28
Tesla:2011-03-01 2011-03-31
Tesla:2011-04-01 2011-04-30
Tesla:2011-05-01 2011-05-31
Tesla:2011-06-01 2011-06-30
Tesla:2011-07-01 2011-07-31
Tesla:2011-08-01 2011-08-31
Tesla:2011-09-01 2011-09-30
Tesla:2011-10-01 2011-10-31
Tesla:2011-11-01 2011-11-30
Tesla:2011-12-01 2011-12-31
Tesla:2012-01-01 2012-01-31
Tesla:2012-02-01 2012-02-29
Tesla:2012-03-01 2012-03-31
Tesla:2012-04-01 2012-04-30
Tesla:2012-05-01 2012-05-31
Tesla:2012-06-01 2012-06-30
Tesla:2012-07-01 2012-07-31
Tesla:2012-08-01 2012-08-31
Tesla:2012-09-01 2012-09-30
Tesla:2012-10-01 2012-10-31
Tesla:2012-11-01 2012-11-30
Tesla:2012-12-01 2012-12-31
Tesla:2013-01-01 2013-01-31
Tesla:2013-02-01 2013-02-28
Tesla:2013-03-01 2013-03-31
Tesla:2013-04-01 2013-04-30
Tesla:2013-05-01 2013-05-31
Tesla:2013-06-01 2013-06-30
Tesla:2013-07-01 2013-07-31
Tesla:2013-08-01 2013-08-31
Tesla:2013-09-01 2013-09-30
Tesla:2013-10-01 2013-10-31
Tesla:2013-11-01 2013-11-30
Tesla:2013-12-01 2013-12-31
Tesla:2014-01-01 2014-01-31
Tesla:2014-02-01 2014-02-28
Tesla:2014-03-01 2014-03-31
Tesla:2014-04-01 2014-04-30
Tesla:2014-05-01 2014-05-31
Tesla:2014-06-01 2014-06-30
Tesla:2014-07-01 2014-07-31
Tesla:2014-08-01 2014-08-31
Tesla:2014-09-01 2014-09-30
Tesla:2014-10-01 2014-10-31
Tesla:2014-11-01 2014-11-30
Tesla:2014-12-01 2014-12-31
Tesla:2015-01-01 2015-01-31
Tesla:2015-02-01 2015-02-28
Tesla:2015-03-01 2015-03-31
Tesla:2015-04-01 2015-04-30
Tesla:2015-05-01 2015-05-31
Tesla:2015-06-01 2015-06-30
Tesla:2015-07-01 2015-07-31
Tesla:2015-08-01 2015-08-31
Tesla:2015-09-01 2015-09-30
Tesla:2015-10-01 2015-10-31
Tesla:2015-11-01 2015-11-30
Tesla:2015-12-01 2015-12-31
Tesla:2016-01-01 2016-01-31
Tesla:2016-02-01 2016-02-29
Tesla:2016-03-01 2016-03-31
Tesla:2016-04-01 2016-04-30
Tesla:2016-05-01 2016-05-31
Tesla:2016-06-01 2016-06-30
Tesla:2016-07-01 2016-07-31
Tesla:2016-08-01 2016-08-31
Tesla:2016-09-01 2016-09-30
Tesla:2016-10-01 2016-10-31
Tesla:2016-11-01 2016-11-30
Tesla:2016-12-01 2016-12-31
Tesla:2017-01-01 2017-01-31
Tesla:2017-02-01 2017-02-28
Tesla:2017-03-01 2017-03-31
Tesla:2017-04-01 2017-04-30
Tesla:2017-05-01 2017-05-31
Tesla:2017-06-01 2017-06-30
Tesla:2017-07-01 2017-07-31
Tesla:2017-08-01 2017-08-31
Tesla:2017-09-01 2017-09-30
Tesla:2017-10-01 2017-10-31
Tesla:2017-11-01 2017-11-30
Tesla:2017-12-01 2017-12-31
Tesla:2018-01-01 2018-01-31
Tesla:2018-02-01 2018-02-28
Tesla:2018-03-01 2018-03-31
Tesla:2018-04-01 2018-04-30
Tesla:2018-05-01 2018-05-31
Tesla:2018-06-01 2018-06-30
Tesla:2018-07-01 2018-07-31
Tesla:2018-08-01 2018-08-31
Tesla:2018-09-01 2018-09-30
Tesla:2018-10-01 2018-10-31
Tesla:2018-11-01 2018-11-30
Tesla:2018-12-01 2018-12-31
Tesla:2019-01-01 2019-01-31
Tesla:2019-02-01 2019-02-28
Tesla:2019-03-01 2019-03-31
Tesla:2019-04-01 2019-04-30
Tesla:2019-05-01 2019-05-31
Tesla:2019-06-01 2019-06-30
Tesla:2019-07-01 2019-07-31
Tesla:2019-08-01 2019-08-31
Tesla:2019-09-01 2019-09-30
Tesla:2019-10-01 2019-10-31
Tesla:2019-11-01 2019-11-30
Tesla:2019-12-01 2019-12-31
Tesla:2020-01-01 2020-01-31
Tesla:2020-02-01 2020-02-29
Tesla:2020-03-01 2020-03-31
Tesla:2020-04-01 2020-04-30
Tesla:2020-05-01 2020-05-31
Tesla:2020-06-01 2020-06-30
Tesla:2020-07-01 2020-07-31
Tesla:2020-08-01 2020-08-31
Tesla:2020-09-01 2020-09-30
Tesla:2020-10-01 2020-10-31
Tesla:2020-11-01 2020-11-30
Tesla:2020-12-01 2020-12-31
Tesla:2021-01-01 2021-01-31
Tesla:2021-02-01 2021-02-28
Tesla:2021-03-01 2021-03-31

            Tesla_unscaled  Tesla_monthly isPartial  scale  Tesla
date
2010-06-30             100            NaN       NaN    NaN    NaN
2010-07-01             100            7.0     False   0.07   7.00
2010-07-02              87            7.0       NaN   0.07   6.09
2010-07-03              17            7.0       NaN   0.07   1.19
2010-07-04              42            7.0       NaN   0.07   2.94

In [4]:
df_tslaTrend.to_csv('Data/tslaTrend2.csv')